// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VPT.Api.Data;

#nullable disable

namespace VPT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817114302_FixListingVehicleMatchRelationship")]
    partial class FixListingVehicleMatchRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VPT.Api.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("VPT.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VehicleTrackingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("VehicleTrackingId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VPT.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleSearchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("VehicleSearchId");

                    b.ToTable("VehicleMatches");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleSearch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<int?>("MaxMileage")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VehicleSearches");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextCheckAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VehicleSearchId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleSearchId")
                        .IsUnique();

                    b.ToTable("VehicleTrackings");
                });

            modelBuilder.Entity("VPT.Api.Models.Notification", b =>
                {
                    b.HasOne("VPT.Api.Models.Listing", "Listing")
                        .WithMany("Notifications")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VPT.Api.Models.VehicleTracking", "VehicleTracking")
                        .WithMany("Notifications")
                        .HasForeignKey("VehicleTrackingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("VehicleTracking");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleMatch", b =>
                {
                    b.HasOne("VPT.Api.Models.Listing", "Listing")
                        .WithMany("VehicleMatches")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VPT.Api.Models.VehicleSearch", "VehicleSearch")
                        .WithMany()
                        .HasForeignKey("VehicleSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("VehicleSearch");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleSearch", b =>
                {
                    b.HasOne("VPT.Api.Models.User", "User")
                        .WithMany("VehicleSearches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleTracking", b =>
                {
                    b.HasOne("VPT.Api.Models.VehicleSearch", "VehicleSearch")
                        .WithOne("VehicleTracking")
                        .HasForeignKey("VPT.Api.Models.VehicleTracking", "VehicleSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleSearch");
                });

            modelBuilder.Entity("VPT.Api.Models.Listing", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("VehicleMatches");
                });

            modelBuilder.Entity("VPT.Api.Models.User", b =>
                {
                    b.Navigation("VehicleSearches");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleSearch", b =>
                {
                    b.Navigation("VehicleTracking");
                });

            modelBuilder.Entity("VPT.Api.Models.VehicleTracking", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
